### ISSUE TITLE
Pythonect Exception Trace contains irrelevant details

### ISSUE THREAD

**Issue by ikotler** [ikotler/pythonect#10]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pythonect/eval.py", line 97, in __run
    raise e
NameError: name 'j' is not defined
```

SHOULD BE MORE LIKE:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'j' is not defined
```

**Comment by dalmoz** [comment]
For global exception, like (let's say your main method is plainly called _main()_):

``` python
import traceback
import sys
...
...
...
try:
 main()
except:
 traceback.print_exc(limit=1)
```

it should minimize the traceback's "deepness".
Is that what you are seeking?

**Comment by ikotler** [comment]
Not quite.

I want to re-write the Exception traceback to be more similar to how it looks like when you're raising an Exception from the interpreter itself.
