### ISSUE TITLE
Can not get pythonect running on Ubuntu. AttributeError

### ISSUE THREAD

**Issue by owigger** [ikotler/pythonect#80]
Hello, I am a newbie both to pythonect and python. I am just trying to get pythonect up and running on plain Ubuntu 18.04, never used python before.

Whatever I do, pythonect crashes horribly with lots of gibberish, Traceback, and the inevitable

               AttributeError: can't set attribute

error. For example:

 $ which pythonect
\~/.local/bin/pythonect

$ pythonect
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[Pythonect 0.6.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> 1+1

Traceback (most recent call last):
  File "\~/.local/lib/python2.7/site-packages/Pythonect-0.6.0-py2.7.egg/pythonect/internal/eval.py", line 792, in eval
    graph = parse(source)
  File "\~/.local/lib/python2.7/site-packages/Pythonect-0.6.0-py2.7.egg/pythonect/internal/eval.py", line 729, in parse
    graph = _graph.Graph()
  File "\~/.local/lib/python2.7/site-packages/Pythonect-0.6.0-py2.7.egg/pythonect/internal/_graph.py", line 47, in __init__
    self.node = _ordereddict.OrderedDict()  # dictionary for node attributes
AttributeError: can't set attribute
\>\>\> 

I tried installing pythonect  with pip, easy_install, or git clone. The result is always the same. I run the nose test in the git checkout:

pythonect$ python setup.py install --user
...
Finished processing dependencies for Pythonect==0.6.0

pythonect$ python setup.py nosetests
1 test_command_mode (test_interpreter.TestPythonectInterpreter) ... ERROR

ERROR: test_command_mode (test_interpreter.TestPythonectInterpreter)
Traceback (most recent call last):
...
  File "\~/pythonect/pythonect/internal/_graph.py", line 47, in __init__
    self.node = _ordereddict.OrderedDict()  # dictionary for node attributes
AttributeError: can't set attribute

Please, I am just following the tutorials. What am I doing wrong??

**Comment by l0b0** [comment]
Hoi @owigger! I was able to reproduce as well:

```
virtualenv --python $(which python2) virtualenv
. virtualenv/bin/activate
pip install pythonect
pythonect
1+1
```

The [metadata](https://github.com/ikotler/pythonect/blob/ac597f9c37b119bafc0e41e67e8a21f02e435752/setup.py#L98) says it's Python 2.7 compatible, but the last [release](https://pypi.org/project/Pythonect/#history) was six years ago, so I suspect it's incompatible with recent Python 2.7 versions.
